Add Path and Orderbook integration tests
XRPLF/xrpl.js pull request #1644
Opened 2021-09-21 22:28 UTC by JST5000

## High Level Overview of Change

Title says it all

### Context of Change

Adding tests for these methods: https://xrpl.org/path-and-order-book-methods.html 

### Type of Change

- [X] Tests (You added tests for code that already exists, or your new feature included in this PR)

## Before / After

Added integration tests for each type of request.

## Test Plan

Integration tests pass

2021-09-21 22:32 UTC, mukulljangid approved these changes

2021-09-22 14:53 UTC, mvadari commented on test/integration/requests/bookOffers.ts
> +describe('BookOffers', function () {
```suggestion
describe('book_offers', function () {
```

2021-09-22 14:53 UTC, mvadari requested changes
All of these tests should check the shape of the response and make sure it matches the object. See the utility tests for examples.

2021-09-24 01:54 UTC, mvadari commented on src/models/methods/ripplePathFind.ts
> +    destination_amount: Amount
whoops
this is why we do integration tests lol

2021-09-24 01:56 UTC, mvadari approved these changes

2021-09-24 17:46 UTC, merged