Add Payment Channel Tests
XRPLF/xrpl.js pull request #1646
Opened 2021-09-21 23:37 UTC by JST5000

## High Level Overview of Change

Title says it all

### Context of Change

This ends up just being ChannelVerify because AuthorizeChannel is handled offline with Signer, and ChannelVerify is the only other PaymentChannel method here: https://xrpl.org/payment-channel-methods.html 

### Type of Change

- [X] Tests (You added tests for code that already exists, or your new feature included in this PR)

## Before / After

Added a test for ChannelVerify

## Test Plan

Integration tests pass

2021-09-22 14:55 UTC, mvadari requested changes
This test should check the shape of the response and make sure it matches the object. See the utility tests for examples.

2021-09-22 14:55 UTC, mvadari commented on test/integration/requests/channelVerify.ts
> +describe('ChannelVerify', function () {
```suggestion
describe('channel_verify', function () {
```

2021-09-23 22:05 UTC, natenichols approved these changes

2021-09-24 01:18 UTC, mvadari approved these changes

2021-09-24 01:19 UTC, natenichols approved these changes

2021-09-24 17:53 UTC, merged