Update package.json for release
XRPLF/xrpl.js pull request #1922
Opened 2022-02-02 23:26 UTC by khancode

## High Level Overview of Change

Update package.json for release

### Type of Change

- [x] Release

2022-02-02 23:27 UTC, mvadari approved these changes

2022-02-03 01:49 UTC, intelliot approved these changes

2022-02-03 01:51 UTC, intelliot requested changes
Sorry, just noticed I already took the 1.3.1 version number. Make this 1.3.2

2022-02-03 01:55 UTC, intelliot requested changes

2022-02-03 01:55 UTC, intelliot commented on package-lock.json
> +      "version": "1.3.1",
```suggestion
      "version": "1.3.2",
```

2022-02-03 01:55 UTC, intelliot commented on packages/ripple-binary-codec/package.json
> +  "version": "1.3.1",
```suggestion
  "version": "1.3.2",
```

2022-02-03 15:59 UTC, mvadari commented
I think @khancode just forgot to push his changes - this was done when we published last night

2022-02-03 16:50 UTC, intelliot approved these changes

2022-02-03 17:04 UTC, merged